apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo_url: AgCLAaQpcxCjPMhoqPGG1+8ANSBaYa5Founmb8HYGrPV7r1pLbJVN2aDAy6FdATuya4Tg0+eC1u6NG9LVYhXeG/huUzJEE7yJG3Ab9MOszWI6PSJXEb3zrG/ZD2WSzuKpLFB5fzrAoq5gfWyS3V4VyzSmO0yt4oBstj0y8+3Fmlkc/EQeQC91yBd8dwM8Qqei1LiBr2azDgtnpdkdOXPVoIZbxWN0D8Q4CNS57yz2TRxDLV1D2qgiaHKZUjQ8//84YZKStJM6sy8thaP3i6d1yB6aFTS7ckNeHl1oM2AleAPKMgGG2MeaPjVTB6WaETLfE4xzbQnFM8qg4OsVyEY6ifjjPZfWpreRQlDyZWGxD9xrcI7C6rIubDAyzVti3D4MW7UzXrto1Q434ypnFicaXAS9hWu4AzkwAy6efwn1hdxEFR2UETZpfyneYAEhv3OWX7xW2GWw+IxkekEDYovNXDq/lYIoMYut8UqkzInNVAcTPVMd2tNV2hbUJSF0ymKyBsI57pDRyu/0onGb0PmtQZ6ZhmfbGaqvnSYB4wsf5waAdx6si4ONzwxwvbu4CMQOWgV6D2VV1F89seuMLC3ZxRxy5IIBVZd+yLjNp2ldhA1lryLbgkfC3qZgfkk9mvPxoDvIPn6PRDA5Y6XiOjTKJvVFOPGwJGoy8lkw4P9DXEV+tCVEPR5Gh79FnCDeQyX6ef/PFZJm9Yrz5f73PGn104qa40cVQHjRWHbjO2l1N9du9DSQKHL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

