apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo_url: AgA/Jwk73mL178/BM/e99uL+oxGWjg/RdhCtQo6+7u//6YwLll7Fwv49Jj4zMqUC9d+iEg1gd8FE74+nzCu7Gs6gnc17z0LZT9W2tE2cAW6wu+Psggln4uSsCi1fPQK63CGXIjpI+4PNGLYzZ2UGeqHiOhmUfqe1YsG3AQQsY7iQ9kAIEm73Br691n9Zy51iCW+w1sYeyj4FaAzWMxyOcaFATIuuVDZn6H+zAwUS+Wjm1wh5WvQ0uZ/Dyb6UwupX+d0UQbt5xaSSfUPrgpMgCUrLEoCt+yislI5K52wP9MVoSazKQpEgoPJPCqOHMugkqFS4R3t4luzZRnhDEEuS4XhZZKXEJH22110BVWPOtPG2n46JIlr5QXDT9r+fmgayx0TV2QYiVVrM4Lo+qT1XXpotjosvSa67pdsFPkwp7ZEoUhAyaaoIq5ss1YaVnQ+qOyMxpyJiAYnvw10eZPLLkkBqV5fJr5zqhZJMAelcoFYcQvLgyfx0+N77q0RHpLRG8zs6wvUx1JZdQE5of+t+GCcaRvrt5nIwgPUJeuwOKfiHCAPK41W5I/Aa9iPidZ8Bi09vPDsm29FfizK6VkUmXd3QS82UOvnEOJT+Br7tbgY6FTPJlE2eBidFO7gF0k8NUE1ZeSI22uyVR4OKvOis2bhuvVbBNu5hXVVSXzQh1zse/MqRx1MY/1z6Y4PGN4x5UFURHyaLbpRrk72g4Sylp2G+U9ZOWK0ecyYjyBD4Srzm4iyMJkE1
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

